### ISSUE TITLE
docker image keycloak-openshift no more available

### ISSUE THREAD

**Issue by Nankh** [microcks/microcks.github.io#5] opened 2019-10-30 13:08 UTC
Hi Team !

We have installed the product on Openshift with the persistent volume option.
3 days ago, we discovered (after a reinit on our side) that the docker image "image: 'jboss/keycloak-openshift:3.4.0.Final'" is no more available on the Docker Hub.

Could you provide a solution to resolve the current bug ?
How can we keep the actual configuration for keycloak ?

Thanks !

**Comment by lbroudoux** [comment] 2019-10-30 17:50
Thanks for raising this issue. This is actually a duplicate of microcks/microcks#169
Tracking this issue with these last one.

**Closed as completed by lbroudoux** 2019-10-30 17:50 UTC
Labels: duplicate
